name: SleepSkip
version: 1.5
main: me.Erotoro.sleepskip.SleepSkip
api-version: '1.21'
folia-supported: true
softdepend: [Essentials, CMI]
authors: [Erotoro]
description: Плагин для пропуска ночи при сне определенного числа игроков.
commands:
  sleep:
    description: Команды SleepSkip
    usage: /sleep <reload|set|status>